apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_NAME: 'mydb'
  DB_USER: 'chang'
  DB_PASSWORD: '123456'
  DB_HOST: 'postgres-service'
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: 'mydb'
  POSTGRES_USER: 'chang'
  POSTGRES_PASSWORD: '123456'
